databases:
  - name: kinderuniversiteit-db
    plan: free

services:
  - type: redis
    name: kinderuniversiteit-redis
    plan: free
    ipAllowList: []

  - type: web
    name: kinderuniversiteit-backend
    env: python
    plan: free
    rootDir: kinderuniversiteit
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FRONTEND_URL
        value: https://demo-frontend-3m8mzjxtl-meshezabel92-8290s-projects.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: kinderuniversiteit-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: kinderuniversiteit-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        value: "sk-dummy-key-please-change-in-dashboard"
